apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-pv
spec:
  capacity:
    storage: 1200Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - allow-delete
    - region us-west-2
  csi:
    driver: s3.csi.aws.com
    volumeHandle: s3-csi-driver-volume
    volumeAttributes:
      bucketName: qwen-models-${AWS_ACCOUNT_ID}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1200Gi
  volumeName: s3-pv
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: model-cache-sa
  namespace: default
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cache-qwen-model
  namespace: default
spec:
  template:
    spec:
      serviceAccountName: model-cache-sa
      restartPolicy: Never
      containers:
      - name: model-downloader
        image: python:3.11-slim
        command:
        - /bin/bash
        - -c
        - |
          pip install huggingface_hub
          
          export MODEL_NAME="Qwen/Qwen2.5-0.5B-Instruct"
          export TEMP_DIR="/tmp/models/$MODEL_NAME"
          export S3_DIR="/s3/models/$MODEL_NAME"
          
          echo "Downloading model: $MODEL_NAME to temporary directory"
          mkdir -p "$TEMP_DIR"
          python -c "
          from huggingface_hub import snapshot_download
          snapshot_download(
              repo_id='$MODEL_NAME',
              local_dir='$TEMP_DIR',
              local_dir_use_symlinks=False
          )
          "
          
          echo "Copying model to S3..."
          mkdir -p "$S3_DIR"
          cp -r "$TEMP_DIR"/* "$S3_DIR/"
          
          echo "Model cached successfully to S3!"
          ls -lah "$S3_DIR"
        resources:
          requests:
            cpu: "2"
            memory: "4Gi"
          limits:
            cpu: "4"
            memory: "8Gi"
        volumeMounts:
        - name: s3-storage
          mountPath: /s3
      volumes:
      - name: s3-storage
        persistentVolumeClaim:
          claimName: s3-pvc
